# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_fecha(object):
    def setupUi(self, Dialog_fecha):
        Dialog_fecha.setObjectName("Dialog_fecha")
        Dialog_fecha.resize(374, 170)
        self.dialog_mensaje = QtWidgets.QLabel(Dialog_fecha)
        self.dialog_mensaje.setGeometry(QtCore.QRect(30, 60, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.dialog_mensaje.setFont(font)
        self.dialog_mensaje.setMouseTracking(False)
        self.dialog_mensaje.setAcceptDrops(False)
        self.dialog_mensaje.setText("")
        self.dialog_mensaje.setObjectName("dialog_mensaje")

        self.retranslateUi(Dialog_fecha)
        QtCore.QMetaObject.connectSlotsByName(Dialog_fecha)

    def retranslateUi(self, Dialog_fecha):
        _translate = QtCore.QCoreApplication.translate
        Dialog_fecha.setWindowTitle(_translate("Dialog_fecha", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_fecha = QtWidgets.QDialog()
    ui = Ui_Dialog_fecha()
    ui.setupUi(Dialog_fecha)
    Dialog_fecha.show()
    sys.exit(app.exec_())
