# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_btn_crear_cliente(object):
    def setupUi(self, btn_crear_cliente):
        btn_crear_cliente.setObjectName("btn_crear_cliente")
        btn_crear_cliente.resize(940, 733)
        self.centralwidget = QtWidgets.QWidget(btn_crear_cliente)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(210, 40, 151, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.ingreso_numero_cedula = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_numero_cedula.setGeometry(QtCore.QRect(50, 120, 131, 16))
        self.ingreso_numero_cedula.setObjectName("ingreso_numero_cedula")
        self.ingreso_nombre_cliente = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_nombre_cliente.setGeometry(QtCore.QRect(80, 150, 101, 16))
        self.ingreso_nombre_cliente.setObjectName("ingreso_nombre_cliente")
        self.recibe_numero_cedula = QtWidgets.QLineEdit(self.centralwidget)
        self.recibe_numero_cedula.setGeometry(QtCore.QRect(180, 120, 113, 20))
        self.recibe_numero_cedula.setText("")
        self.recibe_numero_cedula.setObjectName("recibe_numero_cedula")
        self.recibe_nombre_cliente = QtWidgets.QLineEdit(self.centralwidget)
        self.recibe_nombre_cliente.setGeometry(QtCore.QRect(180, 150, 341, 20))
        self.recibe_nombre_cliente.setText("")
        self.recibe_nombre_cliente.setObjectName("recibe_nombre_cliente")
        self.btn_crear_cliente_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_crear_cliente_2.setGeometry(QtCore.QRect(250, 190, 75, 23))
        self.btn_crear_cliente_2.setObjectName("btn_crear_cliente_2")
        self.ingreso_buscar_cliente_cedula = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_buscar_cliente_cedula.setGeometry(QtCore.QRect(60, 270, 131, 16))
        self.ingreso_buscar_cliente_cedula.setObjectName("ingreso_buscar_cliente_cedula")
        self.btn_buscar_cliente = QtWidgets.QPushButton(self.centralwidget)
        self.btn_buscar_cliente.setGeometry(QtCore.QRect(160, 320, 75, 23))
        self.btn_buscar_cliente.setObjectName("btn_buscar_cliente")
        self.recibe_cedula_buscar = QtWidgets.QLineEdit(self.centralwidget)
        self.recibe_cedula_buscar.setGeometry(QtCore.QRect(190, 270, 113, 20))
        self.recibe_cedula_buscar.setText("")
        self.recibe_cedula_buscar.setObjectName("recibe_cedula_buscar")
        self.mostrar_cliente_recibido = QtWidgets.QTextBrowser(self.centralwidget)
        self.mostrar_cliente_recibido.setGeometry(QtCore.QRect(340, 270, 141, 21))
        self.mostrar_cliente_recibido.setObjectName("mostrar_cliente_recibido")
        self.mostrar_cedula_cliente_buscar = QtWidgets.QLabel(self.centralwidget)
        self.mostrar_cedula_cliente_buscar.setGeometry(QtCore.QRect(490, 270, 91, 16))
        self.mostrar_cedula_cliente_buscar.setText("")
        self.mostrar_cedula_cliente_buscar.setObjectName("mostrar_cedula_cliente_buscar")
        self.mostrar_nombre_cliente_buscar = QtWidgets.QLabel(self.centralwidget)
        self.mostrar_nombre_cliente_buscar.setGeometry(QtCore.QRect(490, 300, 351, 16))
        self.mostrar_nombre_cliente_buscar.setText("")
        self.mostrar_nombre_cliente_buscar.setObjectName("mostrar_nombre_cliente_buscar")
        self.ingreso_cedula_actualizar = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_cedula_actualizar.setGeometry(QtCore.QRect(60, 400, 131, 16))
        self.ingreso_cedula_actualizar.setObjectName("ingreso_cedula_actualizar")
        self.ingreso_nombre_cliente_actualizar = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_nombre_cliente_actualizar.setGeometry(QtCore.QRect(60, 430, 131, 16))
        self.ingreso_nombre_cliente_actualizar.setObjectName("ingreso_nombre_cliente_actualizar")
        self.recibe_cedula_actualizar = QtWidgets.QLineEdit(self.centralwidget)
        self.recibe_cedula_actualizar.setGeometry(QtCore.QRect(190, 400, 113, 20))
        self.recibe_cedula_actualizar.setObjectName("recibe_cedula_actualizar")
        self.recibe_nombre_cliente_actualizar = QtWidgets.QLineEdit(self.centralwidget)
        self.recibe_nombre_cliente_actualizar.setGeometry(QtCore.QRect(190, 430, 341, 20))
        self.recibe_nombre_cliente_actualizar.setObjectName("recibe_nombre_cliente_actualizar")
        self.btn_actualizar_cliente = QtWidgets.QPushButton(self.centralwidget)
        self.btn_actualizar_cliente.setGeometry(QtCore.QRect(240, 470, 91, 23))
        self.btn_actualizar_cliente.setObjectName("btn_actualizar_cliente")
        self.ingreso_cedula_eliminar = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_cedula_eliminar.setGeometry(QtCore.QRect(70, 540, 131, 16))
        self.ingreso_cedula_eliminar.setObjectName("ingreso_cedula_eliminar")
        self.recibe_cedula_eliminar = QtWidgets.QLineEdit(self.centralwidget)
        self.recibe_cedula_eliminar.setGeometry(QtCore.QRect(200, 540, 113, 20))
        self.recibe_cedula_eliminar.setObjectName("recibe_cedula_eliminar")
        self.btn_eliminar_cliente = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eliminar_cliente.setGeometry(QtCore.QRect(240, 570, 91, 23))
        self.btn_eliminar_cliente.setObjectName("btn_eliminar_cliente")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 230, 571, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 360, 571, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 510, 571, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.btn_asociar_factura = QtWidgets.QPushButton(self.centralwidget)
        self.btn_asociar_factura.setGeometry(QtCore.QRect(310, 320, 151, 23))
        self.btn_asociar_factura.setObjectName("btn_asociar_factura")
        btn_crear_cliente.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(btn_crear_cliente)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 21))
        self.menubar.setObjectName("menubar")
        btn_crear_cliente.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(btn_crear_cliente)
        self.statusbar.setObjectName("statusbar")
        btn_crear_cliente.setStatusBar(self.statusbar)

        self.retranslateUi(btn_crear_cliente)
        QtCore.QMetaObject.connectSlotsByName(btn_crear_cliente)

    def retranslateUi(self, btn_crear_cliente):
        _translate = QtCore.QCoreApplication.translate
        btn_crear_cliente.setWindowTitle(_translate("btn_crear_cliente", "MainWindow"))
        self.textBrowser.setHtml(_translate("btn_crear_cliente", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Clientes</span></p></body></html>"))
        self.ingreso_numero_cedula.setText(_translate("btn_crear_cliente", "Documento de Identidad: "))
        self.ingreso_nombre_cliente.setText(_translate("btn_crear_cliente", "Nombre del Cliente:"))
        self.btn_crear_cliente_2.setText(_translate("btn_crear_cliente", "Crear cliente"))
        self.ingreso_buscar_cliente_cedula.setText(_translate("btn_crear_cliente", "Buscar cliente por cedula:"))
        self.btn_buscar_cliente.setText(_translate("btn_crear_cliente", "Buscar cliente"))
        self.mostrar_cliente_recibido.setHtml(_translate("btn_crear_cliente", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Cliente encontrado: </span></p></body></html>"))
        self.ingreso_cedula_actualizar.setText(_translate("btn_crear_cliente", "Documento de Identidad:"))
        self.ingreso_nombre_cliente_actualizar.setText(_translate("btn_crear_cliente", "Nombre nuevo del cliente:"))
        self.btn_actualizar_cliente.setText(_translate("btn_crear_cliente", "Actualizar cliente"))
        self.ingreso_cedula_eliminar.setText(_translate("btn_crear_cliente", "Documento de Identidad:"))
        self.btn_eliminar_cliente.setText(_translate("btn_crear_cliente", "Eliminar cliente"))
        self.btn_asociar_factura.setText(_translate("btn_crear_cliente", "Facturas del cliente buscado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    btn_crear_cliente = QtWidgets.QMainWindow()
    ui = Ui_btn_crear_cliente()
    ui.setupUi(btn_crear_cliente)
    btn_crear_cliente.show()
    sys.exit(app.exec_())
