# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facturas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(120, 40, 141, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.mostrar_cliente_asociado = QtWidgets.QLabel(self.centralwidget)
        self.mostrar_cliente_asociado.setGeometry(QtCore.QRect(270, 45, 221, 21))
        self.mostrar_cliente_asociado.setText("")
        self.mostrar_cliente_asociado.setObjectName("mostrar_cliente_asociado")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 350, 571, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ingreso_fecha_buscar = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_fecha_buscar.setGeometry(QtCore.QRect(80, 380, 111, 16))
        self.ingreso_fecha_buscar.setObjectName("ingreso_fecha_buscar")
        self.recibir_fecha_buscar = QtWidgets.QLineEdit(self.centralwidget)
        self.recibir_fecha_buscar.setGeometry(QtCore.QRect(190, 380, 113, 20))
        self.recibir_fecha_buscar.setObjectName("recibir_fecha_buscar")
        self.btn_buscar_factura = QtWidgets.QPushButton(self.centralwidget)
        self.btn_buscar_factura.setGeometry(QtCore.QRect(200, 410, 81, 23))
        self.btn_buscar_factura.setObjectName("btn_buscar_factura")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 160, 571, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.ingreso_total_buscar = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_total_buscar.setGeometry(QtCore.QRect(320, 380, 91, 21))
        self.ingreso_total_buscar.setObjectName("ingreso_total_buscar")
        self.mostrar_total_buscar = QtWidgets.QLabel(self.centralwidget)
        self.mostrar_total_buscar.setGeometry(QtCore.QRect(420, 380, 91, 21))
        self.mostrar_total_buscar.setText("")
        self.mostrar_total_buscar.setObjectName("mostrar_total_buscar")
        self.ingreso_fecha = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_fecha.setGeometry(QtCore.QRect(56, 100, 131, 20))
        self.ingreso_fecha.setObjectName("ingreso_fecha")
        self.recibir_fecha = QtWidgets.QLineEdit(self.centralwidget)
        self.recibir_fecha.setGeometry(QtCore.QRect(190, 100, 113, 20))
        self.recibir_fecha.setObjectName("recibir_fecha")
        self.btn_crear_factura = QtWidgets.QPushButton(self.centralwidget)
        self.btn_crear_factura.setGeometry(QtCore.QRect(200, 130, 81, 23))
        self.btn_crear_factura.setObjectName("btn_crear_factura")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(90, 190, 401, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.ingreso_nombre_actualizar = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_nombre_actualizar.setGeometry(QtCore.QRect(96, 240, 91, 20))
        self.ingreso_nombre_actualizar.setObjectName("ingreso_nombre_actualizar")
        self.ingreso_cantidad_actualizar = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_cantidad_actualizar.setGeometry(QtCore.QRect(140, 270, 51, 16))
        self.ingreso_cantidad_actualizar.setObjectName("ingreso_cantidad_actualizar")
        self.recibir_nombre_actualizar = QtWidgets.QLineEdit(self.centralwidget)
        self.recibir_nombre_actualizar.setGeometry(QtCore.QRect(190, 240, 113, 20))
        self.recibir_nombre_actualizar.setObjectName("recibir_nombre_actualizar")
        self.recibir_cantidad_actualizar = QtWidgets.QLineEdit(self.centralwidget)
        self.recibir_cantidad_actualizar.setGeometry(QtCore.QRect(190, 270, 113, 20))
        self.recibir_cantidad_actualizar.setObjectName("recibir_cantidad_actualizar")
        self.btn_actualizar_factura = QtWidgets.QPushButton(self.centralwidget)
        self.btn_actualizar_factura.setGeometry(QtCore.QRect(200, 310, 71, 23))
        self.btn_actualizar_factura.setObjectName("btn_actualizar_factura")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 440, 561, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.recibir_fecha_eliminar = QtWidgets.QLineEdit(self.centralwidget)
        self.recibir_fecha_eliminar.setGeometry(QtCore.QRect(194, 460, 113, 20))
        self.recibir_fecha_eliminar.setObjectName("recibir_fecha_eliminar")
        self.ingreso_fecha_eliminar = QtWidgets.QLabel(self.centralwidget)
        self.ingreso_fecha_eliminar.setGeometry(QtCore.QRect(80, 460, 111, 20))
        self.ingreso_fecha_eliminar.setObjectName("ingreso_fecha_eliminar")
        self.btn_eliminar_factura = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eliminar_factura.setGeometry(QtCore.QRect(170, 500, 161, 23))
        self.btn_eliminar_factura.setObjectName("btn_eliminar_factura")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Facturas del cliente: </span></p></body></html>"))
        self.ingreso_fecha_buscar.setText(_translate("MainWindow", "Fecha de facturación:"))
        self.btn_buscar_factura.setText(_translate("MainWindow", "Buscar factura"))
        self.ingreso_total_buscar.setText(_translate("MainWindow", "Total de la factura:"))
        self.ingreso_fecha.setText(_translate("MainWindow", "Fecha de la nueva factura:"))
        self.btn_crear_factura.setText(_translate("MainWindow", "Crear factura"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Agregar productos a la factura creada anteriormente</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p></body></html>"))
        self.ingreso_nombre_actualizar.setText(_translate("MainWindow", "Nombre producto:"))
        self.ingreso_cantidad_actualizar.setText(_translate("MainWindow", "Cantidad:"))
        self.btn_actualizar_factura.setText(_translate("MainWindow", "Agregar"))
        self.ingreso_fecha_eliminar.setText(_translate("MainWindow", "Fecha de facturación:"))
        self.btn_eliminar_factura.setText(_translate("MainWindow", "Eliminar factura del historial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
