# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(90, 30, 431, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.btn_clientes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clientes.setGeometry(QtCore.QRect(230, 120, 111, 41))
        self.btn_clientes.setObjectName("btn_clientes")
        self.btn_fertilizantes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fertilizantes.setGeometry(QtCore.QRect(230, 170, 111, 41))
        self.btn_fertilizantes.setObjectName("btn_fertilizantes")
        self.btn_control_plagas = QtWidgets.QPushButton(self.centralwidget)
        self.btn_control_plagas.setGeometry(QtCore.QRect(220, 230, 131, 41))
        self.btn_control_plagas.setObjectName("btn_control_plagas")
        self.btn_antibioticos = QtWidgets.QPushButton(self.centralwidget)
        self.btn_antibioticos.setGeometry(QtCore.QRect(230, 290, 111, 41))
        self.btn_antibioticos.setObjectName("btn_antibioticos")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuPropietario = QtWidgets.QMenu(self.menubar)
        self.menuPropietario.setObjectName("menuPropietario")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPropietario.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">¡BIENVENIDO A NUESTRA TIENDA!</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_clientes.setText(_translate("MainWindow", "Clientes"))
        self.btn_fertilizantes.setText(_translate("MainWindow", "Fertilizantes"))
        self.btn_control_plagas.setText(_translate("MainWindow", "Control de Plagas"))
        self.btn_antibioticos.setText(_translate("MainWindow", "Antibioticos"))
        self.menuPropietario.setTitle(_translate("MainWindow", "Menú Principal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
